import type { Participant, AthleteResult, LiveState, AuditLog } from '../types/shooting';

export const DEFAULT_YOUTUBE_LIVE_ID = 'dQw4w9WgXcQ'; // Example YouTube Live Video ID (configurable by admin)

export const INITIAL_LIVE_STATE: LiveState = {
    eventId: 'lakshya-2026-championship',
    eventName: 'LAKSHYA 2.0 — ISSF 10M AIR RIFLE & PISTOL CHAMPIONSHIP',
    discipline: '10m_rifle',
    stage: 'QUALIFICATION_LIVE',
    relay: 4,
    youtubeVideoId: 'jfKfPfyJRdk', // Default lofi/live stream demo ID or configurable ID
    streamTitle: 'OFFICIAL LIVE BROADCAST — RELAY 04 QUALIFICATION',
    streamStatus: 'LIVE BROADCAST ACTIVE',
    cameraName: 'MAIN TARGET RANGE CAM 01',
    timerTargetEpoch: Date.now() + 45 * 60 * 1000, // 45 mins remaining
    timerDurationSeconds: 45 * 60,
    isTimerRunning: true,
    updatedAt: Date.now(),
};

export const INITIAL_PARTICIPANTS: Participant[] = [
    {
        id: 'p-021',
        bib: '021',
        name: 'Rahul Kumar',
        gender: 'M',
        category: 'Senior',
        club: 'RVCE Shooting Club',
        college: 'RV College of Engineering',
        noc: 'KA',
        relay: 4,
        firingPoint: 17,
        discipline: '10m_rifle',
    },
    {
        id: 'p-014',
        bib: '014',
        name: 'Arjun Singh',
        gender: 'M',
        category: 'Senior',
        club: 'Precihole Academy',
        college: 'Delhi University',
        noc: 'DEL',
        relay: 4,
        firingPoint: 12,
        discipline: '10m_rifle',
    },
    {
        id: 'p-037',
        bib: '037',
        name: 'Vishal Kumar',
        gender: 'M',
        category: 'Junior',
        club: 'Gandiva Sports',
        college: 'BMSCE Bangalore',
        noc: 'KA',
        relay: 4,
        firingPoint: 5,
        discipline: '10m_rifle',
    },
    {
        id: 'p-008',
        bib: '008',
        name: 'Karan Singh',
        gender: 'M',
        category: 'Senior',
        club: 'Army Marksmanship Unit',
        college: 'NDA Pune',
        noc: 'AMU',
        relay: 4,
        firingPoint: 22,
        discipline: '10m_rifle',
    },
    {
        id: 'p-032',
        bib: '032',
        name: 'Akash Kumar',
        gender: 'M',
        category: 'Junior',
        club: 'NCC Karnataka Battalion',
        college: 'RVCE Bangalore',
        noc: 'KA',
        relay: 4,
        firingPoint: 9,
        discipline: '10m_rifle',
    },
    {
        id: 'p-019',
        bib: '019',
        name: 'Rohit Singh',
        gender: 'M',
        category: 'Youth',
        club: 'Gun For Glory Academy',
        college: 'St. Josephs College',
        noc: 'MH',
        relay: 4,
        firingPoint: 14,
        discipline: '10m_rifle',
    },
    {
        id: 'p-028',
        bib: '028',
        name: 'Ajay Kumar',
        gender: 'M',
        category: 'Senior',
        club: 'Navy Shooting Squad',
        college: 'INS Hansa',
        noc: 'NAV',
        relay: 4,
        firingPoint: 3,
        discipline: '10m_rifle',
    },
    {
        id: 'p-044',
        bib: '044',
        name: 'Manish Rao',
        gender: 'M',
        category: 'Senior',
        club: 'Gagagan Narang Sports',
        college: 'Osmania University',
        noc: 'TS',
        relay: 4,
        firingPoint: 28,
        discipline: '10m_rifle',
    },
    // 10m Air Pistol Participants
    {
        id: 'p-101',
        bib: '101',
        name: 'Saurabh Chaudhary',
        gender: 'M',
        category: 'Senior',
        club: 'UP Rifle Association',
        college: 'Meerut University',
        noc: 'UP',
        relay: 2,
        firingPoint: 10,
        discipline: '10m_pistol',
    },
    {
        id: 'p-102',
        bib: '102',
        name: 'Manu Bhaker',
        gender: 'F',
        category: 'Senior',
        club: 'Haryana Sports Club',
        college: 'DU Lady Shri Ram',
        noc: 'HAR',
        relay: 2,
        firingPoint: 15,
        discipline: '10m_pistol',
    },
];

// Helper to generate 47 realistic qualification decimal shots
function generateSampleShots(targetTotal: number, totalCount: number = 47): number[] {
    const avg = targetTotal / totalCount;
    const shots: number[] = [];
    let currentSum = 0;
    for (let i = 0; i < totalCount; i++) {
        const jitter = (Math.random() * 0.8 - 0.35); // Slight variance around 10.4-10.8
        let s = Math.round((avg + jitter) * 10) / 10;
        if (s > 10.9) s = 10.9;
        if (s < 9.5) s = 9.8;
        shots.push(s);
        currentSum += s;
    }
    return shots;
}

export const INITIAL_ATHLETE_RESULTS: AthleteResult[] = [
    {
        participantId: 'p-021',
        bib: '021',
        name: 'Rahul Kumar',
        noc: 'KA',
        club: 'RVCE Shooting Club',
        relay: 4,
        firingPoint: 17,
        discipline: '10m_rifle',
        qualificationShots: generateSampleShots(506.4, 47),
        qualificationTotal: 648.7,
        qualificationRank: 1,
        qualificationStatus: 'SHOOTING',
        lastShot: 10.8,
        rankDelta: 0,
        finalShots: [10.6, 10.7, 10.8, 10.5, 10.7, 10.8, 10.6, 10.7, 10.9, 10.8, 10.7, 10.8, 10.6, 10.7, 10.8, 10.9, 10.7, 10.8],
        finalTotal: 189.6,
        finalRank: 1,
        finalStatus: 'LIVE',
    },
    {
        participantId: 'p-014',
        bib: '014',
        name: 'Arjun Singh',
        noc: 'DEL',
        club: 'Precihole Academy',
        relay: 4,
        firingPoint: 12,
        discipline: '10m_rifle',
        qualificationShots: generateSampleShots(505.5, 47),
        qualificationTotal: 647.9,
        qualificationRank: 2,
        qualificationStatus: 'SHOOTING',
        lastShot: 10.6,
        rankDelta: 1,
        finalShots: [10.5, 10.6, 10.7, 10.6, 10.7, 10.5, 10.7, 10.8, 10.6, 10.7, 10.6, 10.7, 10.6, 10.7, 10.5, 10.6, 10.7, 10.6],
        finalTotal: 188.9,
        finalRank: 2,
        finalStatus: 'LIVE',
    },
    {
        participantId: 'p-037',
        bib: '037',
        name: 'Vishal Kumar',
        noc: 'KA',
        club: 'Gandiva Sports',
        relay: 4,
        firingPoint: 5,
        discipline: '10m_rifle',
        qualificationShots: generateSampleShots(504.8, 47),
        qualificationTotal: 646.8,
        qualificationRank: 3,
        qualificationStatus: 'SHOOTING',
        lastShot: 10.7,
        rankDelta: -1,
        finalShots: [10.4, 10.5, 10.6, 10.7, 10.5, 10.6, 10.4, 10.6, 10.7, 10.5, 10.6, 10.5, 10.7, 10.6, 10.5, 10.6, 10.4, 10.8],
        finalTotal: 188.2,
        finalRank: 3,
        finalStatus: 'LIVE',
    },
    {
        participantId: 'p-008',
        bib: '008',
        name: 'Karan Singh',
        noc: 'AMU',
        club: 'Army Marksmanship Unit',
        relay: 4,
        firingPoint: 22,
        discipline: '10m_rifle',
        qualificationShots: generateSampleShots(503.2, 47),
        qualificationTotal: 645.2,
        qualificationRank: 4,
        qualificationStatus: 'SHOOTING',
        lastShot: 10.4,
        rankDelta: 0,
        finalShots: [10.3, 10.5, 10.4, 10.6, 10.5, 10.6, 10.5, 10.4, 10.6, 10.5, 10.4, 10.6, 10.5, 10.4, 10.6, 10.5, 10.4, 10.5],
        finalTotal: 187.8,
        finalRank: 4,
        finalStatus: 'LIVE',
    },
    {
        participantId: 'p-032',
        bib: '032',
        name: 'Akash Kumar',
        noc: 'KA',
        club: 'NCC Karnataka Battalion',
        relay: 4,
        firingPoint: 9,
        discipline: '10m_rifle',
        qualificationShots: generateSampleShots(502.9, 47),
        qualificationTotal: 644.8,
        qualificationRank: 5,
        qualificationStatus: 'SHOOTING',
        lastShot: 10.5,
        rankDelta: 0,
        finalShots: [10.2, 10.4, 10.5, 10.3, 10.4, 10.5, 10.4, 10.3, 10.5, 10.4, 10.3, 10.5, 10.4, 10.3, 10.5, 10.4, 10.3, 10.3],
        finalTotal: 186.9,
        finalRank: 5,
        finalStatus: 'LIVE',
    },
    {
        participantId: 'p-019',
        bib: '019',
        name: 'Rohit Singh',
        noc: 'MH',
        club: 'Gun For Glory Academy',
        relay: 4,
        firingPoint: 14,
        discipline: '10m_rifle',
        qualificationShots: generateSampleShots(501.5, 47),
        qualificationTotal: 643.5,
        qualificationRank: 6,
        qualificationStatus: 'SHOOTING',
        lastShot: 10.3,
        rankDelta: 0,
        finalShots: [10.1, 10.3, 10.4, 10.2, 10.3, 10.4, 10.3, 10.4, 10.5, 10.3, 10.4, 10.3, 10.4, 10.3, 10.4, 10.3, 10.2, 10.3],
        finalTotal: 186.2,
        finalRank: 6,
        finalStatus: 'LIVE',
    },
    {
        participantId: 'p-028',
        bib: '028',
        name: 'Ajay Kumar',
        noc: 'NAV',
        club: 'Navy Shooting Squad',
        relay: 4,
        firingPoint: 3,
        discipline: '10m_rifle',
        qualificationShots: generateSampleShots(500.1, 47),
        qualificationTotal: 642.1,
        qualificationRank: 7,
        qualificationStatus: 'SHOOTING',
        lastShot: 10.2,
        rankDelta: 0,
        finalShots: [10.0, 10.2, 10.3, 10.1, 10.2, 10.3, 10.2, 10.3, 10.4, 10.2, 10.3, 10.2, 10.3, 10.2],
        finalTotal: 185.8,
        finalRank: 7,
        finalStatus: 'ELIMINATED',
        eliminatedAtShot: 14,
    },
    {
        participantId: 'p-044',
        bib: '044',
        name: 'Manish Rao',
        noc: 'TS',
        club: 'Gagagan Narang Sports',
        relay: 4,
        firingPoint: 28,
        discipline: '10m_rifle',
        qualificationShots: generateSampleShots(499.0, 47),
        qualificationTotal: 641.0,
        qualificationRank: 8,
        qualificationStatus: 'SHOOTING',
        lastShot: 10.1,
        rankDelta: 0,
        finalShots: [9.9, 10.1, 10.2, 10.0, 10.1, 10.2, 10.1, 10.2, 10.3, 10.1, 10.2, 10.0],
        finalTotal: 185.1,
        finalRank: 8,
        finalStatus: 'ELIMINATED',
        eliminatedAtShot: 12,
    },

    // 10m Air Pistol Sample Results
    {
        participantId: 'p-101',
        bib: '101',
        name: 'Saurabh Chaudhary',
        noc: 'UP',
        club: 'UP Rifle Association',
        relay: 2,
        firingPoint: 10,
        discipline: '10m_pistol',
        qualificationShots: generateSampleShots(510.0, 52),
        qualificationTotal: 588.0,
        qualificationRank: 1,
        qualificationStatus: 'SHOOTING',
        lastShot: 10.7,
        rankDelta: 0,
    },
    {
        participantId: 'p-102',
        bib: '102',
        name: 'Manu Bhaker',
        noc: 'HAR',
        club: 'Haryana Sports Club',
        relay: 2,
        firingPoint: 15,
        discipline: '10m_pistol',
        qualificationShots: generateSampleShots(508.5, 52),
        qualificationTotal: 584.0,
        qualificationRank: 2,
        qualificationStatus: 'SHOOTING',
        lastShot: 10.6,
        rankDelta: 0,
    },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
    {
        id: 'log-001',
        timestamp: Date.now() - 12 * 60 * 1000,
        actorName: 'Scorer SC003',
        actorRole: 'SCORER',
        action: 'SHOT_CORRECTION',
        participantId: 'p-021',
        participantName: 'Rahul Kumar',
        bib: '021',
        shotIndex: 47,
        oldValue: 10.6,
        newValue: 10.8,
        reason: 'Target verification',
    },
    {
        id: 'log-002',
        timestamp: Date.now() - 45 * 60 * 1000,
        actorName: 'Chief Official OF001',
        actorRole: 'OFFICIAL',
        action: 'EVENT_STATE_CHANGE',
        oldValue: 'PREPARATION',
        newValue: 'QUALIFICATION_LIVE',
        reason: 'Relay 04 command signal given',
    },
];
